"""Addon preferences: project roots and registry location.

Pattern reference: dag4blend settings.py (projects / typed props), rewritten.
- source_root (D21/D27): the project source tree; source sets are exported into
  its subfolders, UE mirrors the hierarchy under content_root.
- texture_root (D23): the shared texture library root; texture identity is
  the relative path under it.
- legacy_texture_root (D27): an old absolute texture root used only by the
  explicit one-shot dagormat remap operator.
- registry_path (D17/D28): registry.json generated by the UE plugin
  (master materials etc.); optional — absence only disables warnings.
"""

import bpy


class MHAddonPreferences(bpy.types.AddonPreferences):
    bl_idname = __package__

    source_root: bpy.props.StringProperty(
        name="Source Root",
        description="Project source tree; source sets are exported into its "
                    "subfolders and UE mirrors this hierarchy (D27)",
        subtype="DIR_PATH",
        default="",
    )
    texture_root: bpy.props.StringProperty(
        name="Texture Root",
        description="Shared texture library root; texture paths in manifests "
                    "are relative to it (D23)",
        subtype="DIR_PATH",
        default="",
    )
    legacy_texture_root: bpy.props.StringProperty(
        name="Old Texture Root (Remap)",
        description="Previous absolute texture root; used only when you run "
                    "the one-shot dagormat path remap",
        subtype="DIR_PATH",
        default="",
    )
    registry_path: bpy.props.StringProperty(
        name="Registry (from UE)",
        description="registry.json generated by the UE plugin (D28); "
                    "optional — used for shader_class warnings",
        subtype="FILE_PATH",
        default="",
    )

    def draw(self, _context):
        layout = self.layout
        layout.prop(self, "source_root")
        layout.prop(self, "texture_root")
        layout.prop(self, "legacy_texture_root")
        layout.prop(self, "registry_path")


def get_prefs(context):
    return context.preferences.addons[__package__].preferences


def register():
    bpy.utils.register_class(MHAddonPreferences)


def unregister():
    bpy.utils.unregister_class(MHAddonPreferences)
