#include "Diagnostics/MHDiagnosticRegistry.h"

namespace UE::MimirComposite
{

const TSet<FString>& MHRegisteredErrorCodes()
{
    static const TSet<FString> Codes = {
        TEXT("MH_E_COMPOSITE_CYCLE"),
        TEXT("MH_E_COMPOSITE_GRAMMAR"),
        TEXT("MH_E_COMPOSITE_LEGACY_GENERATION"),
        TEXT("MH_E_DUPLICATE_RANDOM_OPTION_INDEX"),
        TEXT("MH_E_AMBIGUOUS_GENERATED_ASSET"),
        TEXT("MH_E_AMBIGUOUS_RESOURCE_NAME"),
        TEXT("MH_E_AMBIGUOUS_RESOURCE_OWNER"),
        TEXT("MH_E_UNRESOLVED_EXTERNAL"),
        TEXT("MH_E_DANGLING_PARENT"),
        TEXT("MH_E_FBX_TRANSPORT_FAILED"),
        TEXT("MH_E_PARENT_CYCLE"),
        TEXT("MH_E_PLACEMENT_PROFILE_GRAMMAR"),
        TEXT("MH_E_EMPTY_RESOURCE_COLLECTION"),
        TEXT("MH_E_NESTED_COMPOSITE_COLLECTION"),
        TEXT("MH_E_INVALID_COLLECTION_OFFSET"),
        TEXT("MH_E_INVALID_LOD_HIERARCHY"),
        TEXT("MH_E_PARENT_OUTSIDE_RESOURCE"),
        TEXT("MH_E_LOD_LEVELS_SPARSE"),
        TEXT("MH_E_LOD_SLOT_NOT_IN_BASE"),
        TEXT("MH_E_DEPRECATED_LOD_ROWS"),
        TEXT("MH_E_DIVERGENT_REVISIONS"),
        TEXT("MH_E_EXTERNAL_MODIFICATION_CONFIRMATION_REQUIRED"),
        TEXT("MH_E_PARTIAL_PUBLISH"),
        TEXT("MH_E_PAYLOAD_LOCK_TIMEOUT"),
        TEXT("MH_E_RESOURCE_NOT_FOUND"),
        TEXT("MH_E_SOURCE_INDEX_INVALID"),
        TEXT("MH_E_SOURCE_INDEX_PATH_OUTSIDE_ROOT"),
        TEXT("MH_E_SOURCE_INDEX_SNAPSHOT_CHANGED"),
        TEXT("MH_E_INVALID_NODE_MARKERS"),
        TEXT("MH_E_UNRESOLVED_COMPOSITE_REFERENCE"),
        TEXT("MH_E_UNREPRESENTABLE_SCENE_OBJECT"),
        TEXT("MH_E_UNREPRESENTABLE_TRANSFORM"),
        TEXT("MH_E_UNSUPPORTED_NODE_KIND"),
        TEXT("MH_E_PLACEMENT_STATE_DESYNC"),
        TEXT("MH_E_INVALID_RESOURCE_SOURCE"),
        TEXT("MH_E_INVALID_EXPORT_MANIFEST"),
        TEXT("MH_E_RESOURCE_KIND_MISMATCH"),
        TEXT("MH_E_NAN_INF_VALUE"),
        TEXT("MH_E_INVALID_SCALE"),
        TEXT("MH_E_NONCANONICAL_RESOURCE_NAME"),
        TEXT("MH_E_IMPORT_TARGET_OCCUPIED"),
        TEXT("MH_E_UNRESOLVED_MATERIAL_REFERENCE"),
        TEXT("MH_E_EMPTY_MATERIAL_SLOT"),
        TEXT("MH_E_INVALID_MATERIAL_VALUE"),
        TEXT("MH_E_MATERIAL_GRAMMAR"),
        TEXT("MH_E_MATERIAL_NOT_ROUNDTRIPPABLE"),
        TEXT("MH_E_MATERIAL_SLOT_CONFLICT"),
        TEXT("MH_E_NONCANONICAL_TEXTURE_REFERENCE"),
        TEXT("MH_E_TEXTURE_OUTSIDE_ROOT"),
        TEXT("MH_E_UNRESOLVED_TEXTURE_REFERENCE"),
        TEXT("MH_E_UNKNOWN_SCHEMA_VERSION"),
        TEXT("MH_E_NAME_MISMATCH"),
        TEXT("MH_E_TARGET_NAME_COLLISION"),
    };
    return Codes;
}

const TSet<FString>& MHRegisteredWarningCodes()
{
    static const TSet<FString> Codes = {
        TEXT("MH_W_REGISTRY_INVALID"),
        TEXT("MH_W_DAGOR_CONSTRUCT_DROPPED"),
        TEXT("MH_W_REGISTRY_STALE"),
        TEXT("MH_W_DUPLICATE_RESOURCE_NAME"),
        TEXT("MH_W_ORPHAN_REBOUND_CONTENT_DIVERGED"),
        TEXT("MH_W_PROBABLE_RESOURCE_RENAME"),
        TEXT("MH_W_LOD_AUX_NODE_IGNORED"),
        TEXT("MH_W_MANAGED_ASSET_LOCALLY_MODIFIED"),
        TEXT("MH_W_MANAGED_STATIC_MESH_LOCALLY_MODIFIED"),
        TEXT("MH_W_MATERIAL_PAYLOAD_FALLBACK"),
        TEXT("MH_W_MATERIAL_SLOT_NOT_FOUND"),
        TEXT("MH_W_MATERIAL_SLOT_UNMAPPED"),
        TEXT("MH_W_RESOURCE_FAR_FROM_ORIGIN"),
        TEXT("MH_W_PAYLOAD_EXTERNAL_MODIFIED"),
        TEXT("MH_W_UNRESOLVED_PLACEMENT"),
    };
    return Codes;
}

} // namespace UE::MimirComposite
